DATA SCIENCE
    
Analise de dados

pandas - numpy - matplotlib

In [2]:
import pandas as pd

microdadosfifa = pd.read_csv('fifa.csv/fifa.csv')

microdadosfifa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 89 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                18207 non-null  int64
 1   ID                        18207 non-null  int64
 2   Name                      18207 non-null  object
 3   Age                       18207 non-null  int64
 4   Photo                     18207 non-null  object
 5   Nationality               18207 non-null  object
 6   Flag                      18207 non-null  object
 7   Overall                   18207 non-null  int64
 8   Potential                 18207 non-null  int64
 9   Club                      17966 non-null  object
 10  Club Logo                 18207 non-null  object
 11  Value                     18207 non-null  object
 12  Wage                      18207 non-null  object
 13  Special                   18207 non-null  int64
 14  Preferred Foot            18159 non-null  object
 15  International Reputation  18159 non-null  float64
 16  Weak Foot                 18159 non-null  float64
 17  Skill Moves               18159 non-null  float64
 18  Work Rate                 18159 non-null  object
 19  Body Type                 18159 non-null  object
 20  Real Face                 18159 non-null  object
 21  Position                  18147 non-null  object
 22  Jersey Number             18147 non-null  float64
 23  Joined                    16654 non-null  object
 24  Loaned From               1264 non-null   object
 25  Contract Valid Until      17918 non-null  object
 26  Height                    18159 non-null  object
 27  Weight                    18159 non-null  object
 28  LS                        16122 non-null  object
 29  ST                        16122 non-null  object
 30  RS                        16122 non-null  object
 31  LW                        16122 non-null  object
 32  LF                        16122 non-null  object
 33  CF                        16122 non-null  object
 34  RF                        16122 non-null  object
 35  RW                        16122 non-null  object
 36  LAM                       16122 non-null  object
 37  CAM                       16122 non-null  object
 38  RAM                       16122 non-null  object
 39  LM                        16122 non-null  object
 40  LCM                       16122 non-null  object
 41  CM                        16122 non-null  object
 42  RCM                       16122 non-null  object
 43  RM                        16122 non-null  object
 44  LWB                       16122 non-null  object
 45  LDM                       16122 non-null  object
 46  CDM                       16122 non-null  object
 47  RDM                       16122 non-null  object
 48  RWB                       16122 non-null  object
 49  LB                        16122 non-null  object
 50  LCB                       16122 non-null  object
 51  CB                        16122 non-null  object
 52  RCB                       16122 non-null  object
 53  RB                        16122 non-null  object
 54  Crossing                  18159 non-null  float64
 55  Finishing                 18159 non-null  float64
 56  HeadingAccuracy           18159 non-null  float64
 57  ShortPassing              18159 non-null  float64
 58  Volleys                   18159 non-null  float64
 59  Dribbling                 18159 non-null  float64
 60  Curve                     18159 non-null  float64
 61  FKAccuracy                18159 non-null  float64
 62  LongPassing               18159 non-null  float64
 63  BallControl               18159 non-null  float64
 64  Acceleration              18159 non-null  float64
 65  SprintSpeed               18159 non-null  float64
 66  Agility                   18159 non-null  float64
 67  Reactions                 18159 non-null  float64
 68  Balance                   18159 non-null  float64
 69  ShotPower                 18159 non-null  float64
 70  Jumping                   18159 non-null  float64
 71  Stamina                   18159 non-null  float64
 72  Strength                  18159 non-null  float64
 73  LongShots                 18159 non-null  float64
 74  Aggression                18159 non-null  float64
 75  Interceptions             18159 non-null  float64
 76  Positioning               18159 non-null  float64
 77  Vision                    18159 non-null  float64
 78  Penalties                 18159 non-null  float64
 79  Composure                 18159 non-null  float64
 80  Marking                   18159 non-null  float64
 81  StandingTackle            18159 non-null  float64
 82  SlidingTackle             18159 non-null  float64
 83  GKDiving                  18159 non-null  float64
 84  GKHandling                18159 non-null  float64
 85  GKKicking                 18159 non-null  float64
 86  GKPositioning             18159 non-null  float64
 87  GKReflexes                18159 non-null  float64
 88  Release Clause            16643 non-null  object
dtypes: float64(38), int64(6), object(45)
memory usage: 12.4+ MB

In [ ]:
clube_nome = microdadosfifa[['Name', 'Club']]

display(clube_nome)

In [ ]:
acima_25 = microdadosfifa.loc[microdadosfifa['Age'] > 25, ['Name', 'Age']].sort_values(by='Age')

acima_25.head(10)

In [ ]:
overall = microdadosfifa[['Overall', 'Name']]

overall.head(10)

In [ ]:
penaltis = microdadosfifa[['Penalties', 'Name']]

penaltis

In [4]:
colunasSelecionadas = ['Name', 'Club', 'Age', 'Nationality']

nacionalidades = microdadosfifa.filter(items=colunasSelecionadas)

brasileros = nacionalidades.loc[(nacionalidades['Nationality'] == 'Brazil') & (nacionalidades['Age'] > 20)]

brasileros.head(15)

                Name                            Club  Age Nationality
2          Neymar Jr             Paris Saint-Germain   26      Brazil
27          Casemiro                     Real Madrid   26      Brazil
32          Coutinho                    FC Barcelona   26      Brazil
35           Marcelo                     Real Madrid   30      Brazil
39      Thiago Silva             Paris Saint-Germain   33      Brazil
57           Ederson                 Manchester City   24      Brazil
61   Roberto Firmino                       Liverpool   26      Brazil
64       Alex Sandro                        Juventus   27      Brazil
65     Douglas Costa                        Juventus   27      Brazil
75       Fernandinho                 Manchester City   33      Brazil
81           Alisson                       Liverpool   25      Brazil
91          Paulinho  Guangzhou Evergrande Taobao FC   29      Brazil
102            Naldo                   FC Schalke 04   35      Brazil
104          Miranda                           Inter   33      Brazil
106      Filipe Luís                 Atlético Madrid   32      Brazil